### ISSUE TITLE
Alacritty changed config files to toml format

### ISSUE THREAD

**Issue by adrianlzt** [antoniosarosi/pycritty#16]
Workaround, use `yj` to convert the yaml file generated by pycritty to toml.

```
cat $HOME/.config/alacritty/alacritty.yml | yj -yt >  $HOME/.config/alacritty/alacritty.toml
```

**Comment by antoniosarosi** [comment]
Alacritty also has a feature to convert your current Yaml config to Toml. I'll change the source code to use Toml at some point, but I don't have time right now. PRs are welcome though, shouldn't be that hard.

**Comment by antoniosarosi** [comment]
Fixed by https://github.com/antoniosarosi/pycritty/pull/17
