### ISSUE TITLE
I'm not able to run pycritty, relative imports error and not set pycritty as env variable

### ISSUE THREAD

**Issue by JarssS8** [antoniosarosi/pycritty#6]
First of all, when I run the command for install everything (pip install --install-option="--themes=all" pycritty) I have no errors but pycritty is not defined as an env variable. I go to the installation path in my case .local/lib/python3.9/site-packages/pycritty and try to run it as a normal python program (python main.py --font UbuntuMono --size 14 --opacity 0.95)
And this is the error that shows me, it's like can't do relative imports: 
![Screenshot_17](https://user-images.githubusercontent.com/47742360/106607040-21502400-6563-11eb-8511-cf30bf84a40b.png)

I tried to add Pycritty Error on main class for removing the import, but shows the same error with other relative import.

Any idea about why this is not working well?

OS: Garuda (based on Arch)
Desktop: Qtile

**Comment by antoniosarosi** [comment]
When you install packages with ```pip```, the executables are located at ```~/.local/bin```. That directory needs to be on your ```$PATH```. You have to add this line in your ```~/.xprofile```:

```bash
export PATH=$PATH:$HOME/.local/bin
```

The login again and the ```pycritty``` command should be available on any shell.

**Comment by JarssS8** [comment]
That solved my issue, thank you! But now I'm having a problem with opacity. Makes my alacrity terminal darker when the opacity is lower, but don't make it translucent.
![Screenshot_18](https://user-images.githubusercontent.com/47742360/106664344-3c438800-65a5-11eb-9008-06d111b039ce.png)
![Screenshot_19](https://user-images.githubusercontent.com/47742360/106664349-3cdc1e80-65a5-11eb-81fd-53bd9475a3ec.png)

**Comment by antoniosarosi** [comment]
Do you have a wallpaper? If the screen is black, lowering the opacity will make the background darker. Also make sure a compositor is running in the background.

**Comment by JarssS8** [comment]
I was using nitrogen to set the wallpaper and I thought that was ok. Just installing picom and run it on bg is working well.
Thank you so much!
